name: Visual Studio Build Reusable Workflow

on:
  workflow_call:
    inputs:
      solution_path:
        required: true
        type: string
      build_configuration:
        required: false
        type: string
        default: 'Release'

jobs:
  build:
    runs-on: windows-latest  # Visual Studio runs only on Windows
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Full Visual Studio 2022 with Required Workloads
        run: |
          choco install visualstudio2022buildtools --params "--add Microsoft.VisualStudio.Workload.ManagedDesktopBuildTools --add Microsoft.VisualStudio.Workload.NetCoreBuildTools --add Microsoft.VisualStudio.Workload.WebBuildTools --quiet --norestart"

      - name: Install .NET SDK (Latest)
        run: |
          choco install dotnet-sdk --version=8.0.100 -y
          echo "DOTNET_ROOT=C:\Program Files\dotnet" >> $GITHUB_ENV
          echo "C:\Program Files\dotnet" >> $GITHUB_PATH

      - name: Verify .NET SDK Installation
        run: dotnet --info

      - name: Restore NuGet Packages
        run: dotnet restore ${{ inputs.solution_path }}

      - name: Build Solution using Visual Studio
        run: |
          "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\devenv.exe" ${{ inputs.solution_path }} /Build ${{ inputs.build_configuration }}
