name: Visual Studio Build Reusable Workflow

on:
  workflow_call:
    inputs:
      solution_path:
        required: true
        type: string
      build_configuration:
        required: false
        type: string
        default: 'Release'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Full Visual Studio 2022 with Required Workloads
        run: |
          choco install visualstudio2022enterprise --params "--add Microsoft.VisualStudio.Workload.ManagedDesktopBuildTools --add Microsoft.VisualStudio.Workload.NetCoreBuildTools --add Microsoft.VisualStudio.Workload.WebBuildTools --quiet --norestart"
      
      - name: Restore NuGet Packages
        run: nuget restore "${{ inputs.solution_path }}"

      - name: Build Solution using Visual Studio
        shell: cmd
        run: |
          "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\devenv.com" "${{ inputs.solution_path }}" /Build "${{ inputs.build_configuration }}"
